name: 'ecommerce_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_lakehouse'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_lakehouse:
    gold:
      +materialized: materialized_view
      +schema: gold
